platform:ios, '10.0'
use_frameworks!

pod 'SwiftLint'

target 'UIKitPro_Example' do
  pod 'UIKitPro', :path => '../'

  target 'UIKitPro_Tests' do
    inherit! :search_paths
  end
end

target 'UIKitPro_Extension' do
  pod 'UIKitPro', :path => '../'
end

